// Auto-generated by scripts/build-config.js — do not edit by hand.
window.PNP_CONFIG = {
  "sanityProjectId": "",
  "sanityDataset": "production",
  "sanityApiVersion": "2024-01-01",
  "snipcartApiKey": "",
  "snipcartVersion": "3.7.1",
  "newsletterEndpoint": "/api/subscribe",
  "siteOrigin": ""
};
