// Generates `config.js` at build time on Vercel.
// Reads PUBLIC env vars and writes them to a tiny window.PNP_CONFIG object
// that the static HTML pages can read at runtime.
//
// IMPORTANT: only PUBLIC values go here. Secrets (Loops API key, Sanity
// webhook secret) stay server-side in the Vercel Functions and are NEVER
// written to this file.

import { writeFileSync } from "node:fs";
import { resolve, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outputPath = resolve(__dirname, "..", "config.js");

const config = {
  sanityProjectId: process.env.SANITY_PROJECT_ID || "",
  sanityDataset: process.env.SANITY_DATASET || "production",
  sanityApiVersion: process.env.SANITY_API_VERSION || "2024-01-01",
  // Snipcart public API key — safe to expose. Different from a server secret.
  // Find at https://app.snipcart.com → Account → API Keys → Public API Key.
  snipcartApiKey: process.env.SNIPCART_PUBLIC_API_KEY || "",
  // Pin the Snipcart version so a vendor update can't break the cart silently.
  snipcartVersion: process.env.SNIPCART_VERSION || "3.7.1",
  // The newsletter form posts here (a Vercel Function in /api/subscribe.js)
  newsletterEndpoint: "/api/subscribe",
  // Public site origin, used for canonical URLs / OG (optional)
  siteOrigin: process.env.SITE_ORIGIN || "",
};

const banner = "// Auto-generated by scripts/build-config.js — do not edit by hand.\n";
const body = `window.PNP_CONFIG = ${JSON.stringify(config, null, 2)};\n`;

writeFileSync(outputPath, banner + body, "utf8");

const sanityOn = Boolean(config.sanityProjectId);
const snipcartOn = Boolean(config.snipcartApiKey);
console.log(
  `[build-config] wrote ${outputPath} — Sanity ${sanityOn ? "ENABLED (project " + config.sanityProjectId + ")" : "DISABLED (falling back to hardcoded plushies)"}, Snipcart ${snipcartOn ? "ENABLED (" + config.snipcartVersion + ")" : "DISABLED (Adopt CTAs link to /store.html)"}`,
);
